ArticleContentType:
    type: object
    inherits:
        - BaseDomainContentType
    config:
        interfaces:
            - DomainContentType
        fields:
            title:
                type: TextLineFieldDefinition
                resolve: '@=value.getFieldDefinition("title")'
            shortTitle:
                type: TextLineFieldDefinition
                resolve: '@=value.getFieldDefinition("short_title")'
            author:
                type: FieldDefinition
                resolve: '@=value.getFieldDefinition("author")'
            intro:
                type: FieldDefinition
                resolve: '@=value.getFieldDefinition("intro")'
            body:
                type: FieldDefinition
                resolve: '@=value.getFieldDefinition("body")'
            enableComments:
                type: CheckboxFieldDefinition
                resolve: '@=value.getFieldDefinition("enable_comments")'
            image:
                type: RelationFieldDefinition
                resolve: '@=value.getFieldDefinition("image")'
