LandmarkContentUpdateInput:
    type: input-object
    config:
        fields:
            name:
                type: String
            description:
                type: RichTextFieldInput
            photo:
                type: String
            location:
                type: MapLocationFieldInput
